# Generated by Django 4.2.2 on 2023-07-01 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayertime',
            name='masquet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='masque_time', to='main.masque'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff',
            field=models.IntegerField(choices=[(1, 'Imom'), (3, 'Qori'), (2, 'Imom hatib'), (4, 'Muazzin')]),
        ),
    ]
