# Generated by Django 4.2.2 on 2023-07-01 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_prayertime_masquet_alter_staff_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayertime',
            name='admin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_time', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff',
            field=models.IntegerField(choices=[(4, 'Muazzin'), (1, 'Imom'), (3, 'Qori'), (2, 'Imom hatib')]),
        ),
    ]
