# Generated by Django 4.2.2 on 2023-07-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_prayertime_admin_alter_staff_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayertime',
            name='Afternoon',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='prayertime',
            name='Evening',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='prayertime',
            name='Midnight',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='prayertime',
            name='Night',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='prayertime',
            name='morning',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff',
            field=models.IntegerField(choices=[(3, 'Qori'), (2, 'Imom hatib'), (4, 'Muazzin'), (1, 'Imom')]),
        ),
    ]
