# Generated by Django 4.2.2 on 2023-07-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_prayertime_afternoon_alter_prayertime_evening_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prayertime',
            name='admin',
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff',
            field=models.IntegerField(choices=[(1, 'Imom'), (2, 'Imom hatib'), (3, 'Qori'), (4, 'Muazzin')]),
        ),
    ]
