# Generated by Django 4.2.2 on 2023-07-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_prayertime_admin_alter_staff_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff',
            field=models.IntegerField(choices=[(3, 'Qori'), (2, 'Imom hatib'), (4, 'Muazzin'), (1, 'Imom')]),
        ),
    ]
